import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/common-sidebar/side-menu";
// import {
//   SidebarMenuButton,
//   // SidebarInset,
//   SidebarProvider,
//   SidebarTrigger,
// } from "@/components/ui/sidebar";
import Link from "next/link";
import { Separator } from "@/components/ui/separator";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { BadgeCheck, Bell, CreditCard, LogOut, Sparkles } from "lucide-react";
import { DropdownMenuContent } from "@radix-ui/react-dropdown-menu";
import LoginForm from "@/components/ui/login-form";
import { Toaster } from "@/components/ui/sonner"
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import Header from "@/components/common-components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zen Wellness Lounge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {false ? (
          <LoginForm className={""} />
        ) : (
          // <SidebarProvider>
          // <AppSidebar />
          <div className="flex flex-col w-full">
            <Header />


            <main className="w-full p-4">{children}</main>
            <footer className="fixed backcolor-purpole text-white bottom-0 z-50 w-full bg-white dark:bg-gray-900  border-t p-8">
              <div className=" text-center mb-0 md:text-md text-md">
                Copyright @ 2025 ZenWellness Lounge. Concept by{" "}
                <Link href="https://irepute.in/">repute</Link>
              </div>
            </footer>
          </div>
          // </SidebarProvider>
        )}
        <Toaster position="top-center" />
        {/* <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
              <div className="flex items-center gap-2 px-4">
                <SidebarTrigger className="-ml-1" />

              </div>
            </header>
            <main className="w-full p-4">{children}</main>
          </SidebarInset>
        </SidebarProvider> */}
      </body>
    </html>
  );
}
