import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/common-sidebar/side-menu";
import {
  SidebarMenuButton,
  // SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import Link from "next/link";
import { Separator } from "@/components/ui/separator";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { BadgeCheck, Bell, CreditCard, LogOut, Sparkles } from "lucide-react";
import { DropdownMenuContent } from "@radix-ui/react-dropdown-menu";
import LoginForm from "@/components/ui/login-form";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zen Wellness Lounge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {false ? (
          <LoginForm className={""} />
        ) : (
          <SidebarProvider>
            <AppSidebar />
            <div className="flex flex-col w-full">
              <header className="sticky top-0 z-50 w-full bg-white dark:bg-gray-900 shadow-md p-2 flex items-center">
                <div className="flex justify-between items-center w-full">
                  <div className="flex justify-start items-center">
                    <SidebarTrigger />
                    <Separator className="h-6 w-px bg-black mx-2" />
                    <h1 className="text-lg font-semibold pl-2">
                      Zen Wellness Lounge
                    </h1>
                  </div>
                  <div className="flex items-center ml-auto">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <SidebarMenuButton
                          size="lg"
                          className="data-[state=open]:bg-gray-300 data-[state=open]:text-sidebar-accent-foreground"
                        >
                          <Avatar className="h-8 w-8 rounded">
                            <AvatarImage
                              src="https://github.com/shadcn.png"
                              alt="@shadcn"
                            />
                            <AvatarFallback>CN</AvatarFallback>
                          </Avatar>

                          {/* <ChevronsUpDown className="ml-auto size-4" /> */}
                        </SidebarMenuButton>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent
                        className="w-[--radix-dropdown-menu-trigger-width] bg-gray-300 p-4 min-w-56 rounded-lg"
                        side={"bottom"}
                        align="end"
                        sideOffset={4}
                      >
                        <DropdownMenuLabel className="p-0 font-normal">
                          <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                            <Avatar className="h-8 w-8 rounded-lg">
                              <AvatarImage
                                src="https://github.com/shadcn.png"
                                alt="@shadcn"
                              />
                              <AvatarFallback>CN</AvatarFallback>
                            </Avatar>
                            <div className="grid flex-1 text-left text-sm leading-tight">
                              <span className="truncate font-semibold">
                                Zen Lounge
                              </span>
                              <span className="truncate text-xs">
                                zenlounge@gmail.com
                              </span>
                            </div>
                          </div>
                        </DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                          <DropdownMenuItem>
                            <Sparkles />
                            Upgrade to Pro
                          </DropdownMenuItem>
                        </DropdownMenuGroup>
                        <DropdownMenuSeparator />
                        <DropdownMenuGroup>
                          <DropdownMenuItem>
                            <BadgeCheck />
                            Account
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <CreditCard />
                            Billing
                          </DropdownMenuItem>
                          <DropdownMenuItem>
                            <Bell />
                            Notifications
                          </DropdownMenuItem>
                        </DropdownMenuGroup>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem>
                          <LogOut />
                          Log out
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              </header>

              <main className="w-full p-4">{children}</main>
              <footer className="sticky bottom-0 z-50 w-full bg-white dark:bg-gray-900  border-t p-4">
                <p className="mb-0 md:text-sm text-xs">
                  Copyright @ 2025 ZenWellness Lounge. Concept by{" "}
                  <Link href="https://irepute.in/">repute</Link>
                </p>
              </footer>
            </div>
          </SidebarProvider>
        )}
        <Toaster position="top-center" />
        {/* <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
              <div className="flex items-center gap-2 px-4">
                <SidebarTrigger className="-ml-1" />

              </div>
            </header>
            <main className="w-full p-4">{children}</main>
          </SidebarInset>
        </SidebarProvider> */}
      </body>
    </html>
  );
}
